layout_spectrum: 0.2614337
typography_spectrum: 0.9076044
color:
  saturation: 0.574901
  lightness: 0.1343649
  brandStrength: 0.4155829
  rhythmicContrast: 0.4864575
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Www.campingworldofsouthalabama.com
